name: "Clase 2"

on: 
    push:
        branches:
        - main

jobs:
    first_jobs:
        runs-on: ubuntu-latest

        steps:
            - name: Hola Mundo
              run: echo "Hola mundo"

    second_job:
        runs-on: ubuntu-latest
        steps:
            - name: Hola Mundo
              run: echo "Hola mundo"
            - name: Hola Mundo 2
              run: echo "Hola mundo 2"
