name: "Clase 2"

on: 
    push:
        branches:
        - main

jobs:
    first_job:
        runs-on: ubuntu-latest

        env:
            NAME: "Codigo Facilito"

        steps:
            - name: Hola Mundo
              run: echo "Hola mundo" ${env.NAME}

    second_job:
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push'  }}
        needs: first_job
        runs-on: ubuntu-latest
        steps:
            - name: Hola Mundo
              run: echo "Hola mundo"
            - name: Hola Mundo 2
              run: echo "Hola mundo 2"
