name: "Clase 2"

on: 
    push:
        branches:
        - main

jobs:
    first_job:
        name: "Mi primer job"
        runs-on: ubuntu-latest

        outputs:
            first_output: ${{ steps.step_save.outputs.myVariable }}

        env:
            NAME: "Codigo Facilito"

        steps:
            - name: Hola Mundo
              run: echo "Hola mundo ${NAME}"

            - name: working dir
              run: ls -lA

            - name: Checkout
              uses: actions/checkout@v4

            - name: working dir after action
              run: ls -lA

            - name: gihub options
              run: echo "$GITHUB_OUTPUT"

            - name: save another value
              id: step_save
              run: echo "myVariable=Hola" >> $GITHUB_OUTPUT

            - name: print another value
              run: echo "${{ steps.step_save.outputs.myVariable }}"

    second_job:
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push'  }}
        needs: first_job
        runs-on: ubuntu-latest

        env:
            SALIDA: ${{ needs.first_job.outputs.first_output }}

        steps:
            - name: Hola Mundo
              run: echo "Hola mundo"
            - name: Hola Mundo 2
              run: echo "Hola mundo 2"
            - name: Hola Mundo 3
              run: echo "Mi variable es ${SALIDA}"
