name: strategy

on:
  push:
    branches: [ main ]

jobs:
  first_job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message:
          - "Hola"
          - "Mundo"
          - "Codigo Facilito"

    steps:
      - name: Hola Mundo
        run: echo "${{ matrix.message }}"