name: test-exam

on: 
    workflow_dispatch:
        inputs:
            test_suite:
                description: Test suite
                type: choice
                options:
                    - functional
                    - regression

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hacemos pull del codigo"
            - run: echo "Correr migraciones"
            - run: echo "Correr pruebas"
            - run: echo "Correr comandos de produccion"
            - name: Echo test suite
              run: |
                echo "Test suite: ${{ inputs.test_suite }}"

